apiVersion: constraints.gatekeeper.sh/v1beta1
kind: ClusterSecretStoreControl
metadata:
  name: clustersecretstorecontrol
spec:
  match:
    kinds:
    - apiGroups:
      - external-secrets.io
      kinds:
      - ExternalSecret
  parameters:
    ClusterSecretStore:
    - allowednamespace:
      - istio-system
      - istio-ingressgateway
      - argocd
      name: vault-example-1
    - allowednamespace:
      - istio-system
      - istio-ingressgateway
      - mysoftware
      - argocd
      - myloomtest
      name: vault-example-2
    - allowednamespace:
      - generalservice
      - mappingservice
      name: vault-example-3
