apiVersion: constraints.gatekeeper.sh/v1beta1
kind: ClusterSecretStoreControl
metadata:
  name: clustersecretstorecontrol 
spec:
  match:
    kinds:
      - apiGroups: ["external-secrets.io"]
        kinds: ["ExternalSecret"]
  parameters:
    ClusterSecretStore:
      - name: vault-example-1
        allowednamespace:
          - istio-system
          - istio-ingressgateway
          - argocd
      - name vault-example-2
        allowednamespace:
          - istio-system
          - istio-ingressgateway
          - mysoftware
          - argocd
      - name vault-example-3
        allowednamespace:
          - generalservice
          - mappingservice
